### ISSUE TITLE
natural park oasis is impossible

### ISSUE THREAD

**Issue by mauriOZDEV** [JiroCab/Nyfalis#16]
hi, i really like this mod and i been playing it for some time, untill i reach natural park oasis, and it is impossible to beat for logistic issues and because of the landing zone.
my recomendations are: adding lead to the desert zone or better distribution of the landing zone.
thanks for reading and sorry for the grammar =p
pd: i dont known if the map is tested or i am too bad or it is impossible really, but i tried sixteen times before publishing this issue but i put it on hard or exteme, not medium =)

**Comment by JiroCab** [comment]
it's possible but quite rough to do
and i been lazy forgot to change the difficulty of the sector too
but this has been noted

cheers and thanks for playing ^^

**Comment by mauriOZDEV** [comment]
thanks you for making an amazing mod
